[package]
name = "sdk-gateway"
version = "0.1.0"
authors = ["Julius de Bruijn <julius.debruijn@360dialog.com>"]

[dependencies]
hyper = { git = "https://github.com/hyperium/hyper" }
pretty_env_logger = "0.2"
