[package]
name = "sdk-gateway"
version = "0.1.0"
authors = ["Julius de Bruijn <julius.debruijn@360dialog.com>"]
build = "build.rs"

[dependencies]
hyper = { git = "https://github.com/hyperium/hyper" }
http = "0.1"
log = "0.4"
env_logger = "0.5"
lazy_static = "1.0"
gelf = "0.2"
pretty_env_logger = "0.2"
ring = "0.12"
serde = "1.0"
serde_json = "1.0"
chan-signal = "0.3"
chan = "0.1"
serde_derive = "1.0"
toml = "0.4"
bytes = "0.4"
prost = "0.3"
prost-derive = "0.3"
chrono = "0.4"
argparse = "0.2"
futures = "0.1"
base64 = "0.6"
rand = "0.5.0-pre.1"
uuid = { version = "0.6", features = ["serde", "v4"] }
tokio = "0.1"
tokio-threadpool = "0.1"
hex = "0.3"
r2d2 = "0.8"
r2d2_postgres = "0.14"
indoc = "0.2"
crossbeam = "0.3"
aerospike = "0.2"
prometheus = { git = "https://github.com/flier/rust-prometheus.git", branch = "protobuf-1.6" }

[build-dependencies]
prost-build = "0.3"

[dependencies.postgres]
version = "0.15"
default-features = true
features = ["with-chrono"]
