version: '3'
services:
  scylladb:
    image: scylladb/scylla
    ports:
      - "9042:9042"
    dns: 10.51.240.10
    dns_search:
      - default.svc.cluster.local
      - svc.cluster.local
      - cluster.local
      - local
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: "localhost"
      KAFKA_CREATE_TOPICS: "test.rule-engine.sdk-events:1:1"
